czbiohub-sf/iohub

setup.cfg
This PR adds `zarr` to `iohub`'s `install_requires`.
A from-scratch install of `iohub` showed that `from iohub.reader import ImageReader` fails since `zarr` isn't an explicit dependency.
=> Add zarr to install_requires

iohub/cli/cli.py, iohub/pycromanager.py, iohub/reader.py, iohub/zarrfile.py, tests/reader/test_reader.py, tests/reader/test_zarrfile.py
This PR does a shallow renaming: the legacy `WaveorderReader` class is now `ImageReader`. Otherwise API remains the same.
=> Rename `WaveorderReader` to `ImageReader`

examples/single_fov_ome_zarr.py, iohub/ngff.py, tests/ngff/test_ngff.py
Requested by #45.
Related to #58.
=> Get NGFF channel index from name

examples/multi_fov_hcs_ome_zarr.py, examples/single_fov_ome_zarr.py
Swap the output directory from $HOME to a temporary directory.
I notice that the examples can be run as notebooks, if we're ok with removing this feature I could add `__name__ == __main__` to this PR.
=> Makes examples output directory temporary

iohub/ngff.py
`os.path.join` uses different separators (`/` or `\`) to join paths, but the NGFF spec only uses `/`. 
The pydantic validator correctly only admits `/`, so it complained when I tried to convert a dataset to ome-zarr v0.4 using the iohub converter on the hummingbird machine. 
I have tested this fix on hummingbird and my personal machine.
=> Use fixed separator `/` to join row_name and col_name

iohub/convert.py, iohub/multipagetiff.py, iohub/upti.py
Fixes #82 and https://github.com/mehta-lab/recOrder/issues/327#issuecomment-1479897823.
The converter will now log a warning and fill with zeros instead of throwing an error if certain images are not present in the OME-TIFF series.
Edit: Test that repeated reads return the same values.
```python
In [1]: from iohub.reader import imread
In [2]: reader = imread('/hpc/projects/compmicro/rawdata/other/NIC QLIPP/2022_12_01 PtK cells/FOV1_1')
In [4]: reader.get_zarr(0)[0,-1,:,500,500]
Out[4]:
array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
0,   0,   0,   0,   0,   0,   0, 631,   0,   0,   0,   0,   0,
0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
0,   0], dtype=uint16)
In [5]: reader.get_zarr(0)[0,-1,:,500,500]
Out[5]:
array([  0,   0,   0,   0,   0,   0, …
```
=> Initialize Zarr arrays in TIFF readers as zero-filled

pyproject.toml
Fixes #123. I needed a dev installation to test the `convert` command. 
Copied from https://stackoverflow.com/a/71488066, and I tested that it works. Feel free to modify.
=> Fix `setuptools-scm` installation error

.github/workflows/docs.yml, docs/gh-pages-redirect.html, docs/source/_static/switcher.json, docs/source/conf.py, setup.cfg
Building docs with sphinx-multiversion does not automatically generate a root `index.html` file. So currently the [czbiohub.github.io/iohub/](https://czbiohub.github.io/iohub/) link is broken, and the docs for main needs to be accessed from https://czbiohub.github.io/iohub/main.
The index needs to be manually generated according to the extension's [documentation](https://holzhaus.github.io/sphinx-multiversion/master/github_pages.html#redirecting-from-the-document-root).
=> Fix multiversion links

.pre-commit-config.yaml, iohub/reader.py
When I saw an `iohub info` result like this:
```
=== Summary ===
Format:		 omezarr v0.4
Axes:		 T (time); C (channel); Z (space); Y (space); X (space); 
Channel names:	 ['GFP EX488 EM525-45', 'mCherry EX561 EM600-37']
Row names:	 ['0']
Column names:	 ['0']
Wells:		 1
```
I didn't realize that the zarr store actually had multiple positions. 
This PR adds one line to the output to show the user the total number of positions:
```
Positions:	 5
```
=> Print number of positions in `iohub info`

iohub/ndtiff.py, setup.cfg
Resolves #124.
This bumps `ndtiff` to 2.1.0 so that we can use the automatic axes sorting instead of pulling our own.
Currently CI only tests for NDTIFFv2 datasets. @ieivanov Should we add some v3 datasets to the pool?
=> Update NDTIFF reader

tests/ngff/test_ngff.py
This test has been causing flakiness in CI (e.g. [this run](https://github.com/czbiohub-sf/iohub/actions/runs/5261313496/jobs/9509282931)). This PR releases timing requirement from 200 ms to 2000 ms and limits the max examples to 16.
=> Release timing requirement for I/O-heavy test

iohub/ngff.py, tests/ngff/test_ngff.py
~Proposed solution for #141 in https://github.com/czbiohub/iohub/issues/141#issuecomment-1575062339.~
Edit: The mantis project has decided to create the Zarr hierarchy before distributed processing. So this PR no longer requires review from that perspective. However, I think it is still useful for combining existing datasets in general, and this pooling can potentially benefit projects such as machine learning.
Usage pattern:
```py
from iohub.ngff import open_ome_zarr, Plate
with open_ome_zarr("hcs.zarr") as old_plate:
fovs = dict(old_plate.positions())
with open_ome_zarr("fov.zarr") as old_position:
fovs["Z/1/0"] = old_position
new_plate = Plate.from_positions("combined.zarr", fovs)
```
=> Gather FOVs into plates

setup.cfg
Zarr 2.16 introduces a change related to tifffile. Since we pinned tifffile to an older version this may have broke our TIFF converters.
Temporarily mitigates #164
=> Pin zarr version to avoid tifffile issue

iohub/reader.py, tests/cli/test_cli.py, tests/conftest.py
This PR prints a `(Z, Y, X) scale (um)` line when you call `iohub info` on an `ndtiff` dataset or an `ngff.Position`. 
Example output:
```iohub info /hpc/instruments/cm.mantis/2023_08_09_HEK_PCNA_H2B/pcna_rac1_virtual_staining_1/pcna_rac1_virtual_staining_labelfree_1/
Reading file:	 /hpc/instruments/cm.mantis/2023_08_09_HEK_PCNA_H2B/pcna_rac1_virtual_staining_1/pcna_rac1_virtual_staining_labelfree_1
Dataset opened
=== Summary ===
Format:		 ndtiff
Positions:	 216
Time points:	 1
Channels:	 1
Channel names:	 ['BF']
(Z, Y, X) shape:	 (120, 1024, 1224)
(Z, Y, X) scale (um):	 (0.143, 0.1494, 0.1494)
iohub info /hpc/projects/comp.micro/mantis/2023_08_09_HEK_PCNA_H2B/0-zarr/pcna_rac1_virtual_staining_1/pcna_rac1_virtual_staining_labelfree_1.zarr/0/0/0/
Reading file: …
```
=> Print scale in `iohub info`

iohub/ngff.py, tests/test_converter.py
Set FOV-level transformation to identity upon creation of the first array.
=> Only set array transformation upon creation of FOVs

iohub/cli/cli.py, iohub/convert.py, iohub/ndtiff.py, iohub/reader_base.py, tests/cli/test_cli.py, tests/ngff/test_ngff.py, tests/reader/test_pycromanager.py, tests/test_converter.py
Convert non-HCS string-valued ND-TIFF position coordinate into column names of an HCS OME-Zarr store.
=> Convert ND-TIFF position label

iohub/cli/cli.py, iohub/convert.py, iohub/ndtiff.py, tests/cli/test_cli.py
This PR enables XYZ chunking at zarr conversion and speeds up `ndtiff` conversion following [this](https://github.com/czbiohub-sf/compmicro-sandbox/blob/master/iohub_scripts/convert/convert_isim_fish.py) example.
Fixes #176, Fixes #177 
To use, call `iohub convert -i /path/to/input/ -o /path/to/output.zarr/ --chunks XYZ`. Z stacks may be split into multiple chunks if they are larger than `MAX_CHUNK_SIZE` bytes.
We should use this code to convert future datasets and we should also re-convert older large datasets to reduce the number of small files on our storage.
Let's build on this code and make the converter work well. So far, I've tested it only with `pytest` and latest mantis `ndtiff` datasets. Currently, the converter effectively splits into two paths, depending on whether you're …
=> Enable XYZ chunking at conversion

iohub/ndtiff.py
Properly read ndtiff data when p_idx=0 is missing, which can happen if autofocus fails on first time point, but engages properly later.
=> Better NDTiff reading when the first position is missing

iohub/convert.py
This `np.prod` call was overflowing when converting our data and resulting in invalid chunks.
=> Fix product integer overflow

iohub/convert.py, iohub/multipagetiff.py
The OpenCell acquisition starts with a large number of positions in the position list, but only some of those are actually imaged. When we save the data, we need to use a continuous position index starting at 0 because of a Micro-manager bug: https://github.com/micro-manager/micro-manager/issues/1723, i.e. if we are imaging positions `(5, 6, 13, 12)` in the position list, they are saved with index `(0, 1, 2, 3)`. In this case, we need to parse the correct position label from the tif filename.
I've implemented this as a special version of Micro-manager metadata. If we change the MM version on the Dragonfly microscope (unlikely) or the "raw_data" prefix (also very unlikely) this code will not work an will need to be modified. I've also switched the order of `_gather_index_maps()` and …
=> OpenCell reader extension

iohub/display_utils.py
Suggesting a modification of the display color for some fluorophores.
I found that Cy5 and mCherry were both plotted in magenta, when they actually have quite different emission spectrum.
Alexa561 was also listed under both magenta and yellow colors.
=> Modified fluorophore color code

iohub/convert.py, tests/test_converter.py
Breaking up the ndtiff image plane metadata, which can be quite large, per position
=> Save ndtiff image plane metadata per position

iohub/convert.py
In the case where you image all columns at row 35 (i.e. 1x38 FOVs) of a 38x38 grid you'd end up with incorrect determination of the number of rows and columns as (35, 38). This PR fixes this bug.
=> Fix bug determining number of rows and cols

iohub/mmstack.py
This PR fixes a bug in reading data acquired with the Dragonfly acquisition pipeline.
In the Dragonfly acquisition pipeline, we start with a large position list, but not all of these positions may be acquired. The resulting `ome.tif` dataset will have a large number of positions in the MM metadata, but fewer data series. In this PR, I limit the `xdata` size to the number of actual positions acquired. The site index is only accessible from the filename. There may be a better way to get the number of tif files and their filenames than doing a glob in the root directory.
=> Fix bug reading dragonfly acquisitions

iohub/convert.py, tests/ngff/test_ngff.py
This PR cleans up the converter logging:
* Only one warning is issued per P-T-C, rather than issuing a warning for every P-T-C-Z
* FOV name is included in the warning message
* Logger console output is redirected to `tqdm.write()` for cleaner output - see before and after images
Before:
After:
=> Modify warning

iohub/display_utils.py, setup.cfg, tests/ngff/test_ngff.py
=> Add Y5 to orange display color group

docs/source/_static/switcher.json
The switcher fix in #223 was missing the project root path segment.
=> Fix docs switcher path

iohub/ngff/nodes.py, tests/pyramid/test_pyramid.py
Hi, I noticed this bug a while ago, but the change was lost in #221 
The spatial scaling should increase as we make the images smaller so they are all the same size.
This doesn't affect napari, but it does for other viewers (e.g. neuroglancer).
=> Fixing pyramid scaling factor

iohub/ngff/models.py
Use annotation instead of field for tagged union to allow `list[AxisMeta]` to work with pydantic 2.9.0.
Also removed non-standard axis which was added in anticipation of [RFC-3](https://github.com/ome/ngff/pull/239) to make the fix easier.
=> Use annotation instead of field for tagged union

iohub/ngff/__init__.py
The latest iohub will break VisCy's hcs.py as it imports the `ImageArray`.
This PR exposes `ImageArray` to support the old usecase. 
happy to modify viscy otherwise
=> Export `ImageArray` from the `ngff` module

tests/ngff/test_ngff_utils.py
Fixing process_single_position_setup() to pass tests. The chunks should be (1,1,Z,Y,X) since we parallelize over T, C.
=> Fixing tests for process_single_position_setup()

iohub/reader.py, tests/cli/test_cli.py, tests/test_reader.py
This addresses issue #247 by adding the store size and array size in GB. This is useful and simple metadata. 
I wanted to know how much memory to request for caching datasets.
=> Add decompressed OME-Zarr dataset size to iohub info

iohub/rename_wells.py
CSV files generated on Windows contain the `u'\ufeff'` byte order mark (BOM) character. By specifying the `utf-8-sig` encoding we remove the BOM character when reading the file.
=> Remove BOM from well name

iohub/ngff/nodes.py, setup.cfg, tests/ngff/test_ngff.py
=> Add conversion of ImageArray to dask

iohub/ndtiff.py
The calculations of `z-step_um` fails if the dataset has only a single z slice. In that case, `ZPosition_um_Intended` exists in the metadata, but the dataset does not have images at `z_idx = 1`. Here I've wrapped the calculation of `z-step_um` in a try/except statement which would catch both cases.
@ahillsley please confirm that this PR fixes your issue and approve it.
=> More robust calculation of "z-step_um" for ndtiff datasets

iohub/mmstack.py
Use empty defaults when position, channel, and prefix metadata is not available.
Seems to fix https://github.com/czbiohub-sf/iohub/issues/267.
=> Fix reading Dragonfly non-OpenCell datasets with incomplete metadata

iohub/mm_fov.py, tests/mmstack/test_mmstack.py
Make MM FOVs special cases when comparing, since they do not have individual paths.
Resolve #157.
=> Compare MM FOVs

iohub/ngff/nodes.py, tests/ngff/test_ngff.py
- This PR adds enables setting the contrast limits of a `ngff.Position` per channel.
=> Set contrast limits method

iohub/ngff/nodes.py, tests/ngff/test_ngff.py
Implement https://github.com/mehta-lab/waveorder/issues/439#issuecomment-2706996852.
By default, disallow overwriting paths that do not contain `.zarr` to reduce data loss incidents caused by erroneous user input.
This can be disabled to restore spec conformance.
=> Check overwrite path

iohub/ngff/models.py, iohub/reader.py
This PR contains minor spec-mismatch bug fixes to enable `iohub info` to work with `.zarr` files converted from `.nd2` using [`bioformats2raw` conversion tool](https://github.com/glencoesoftware/bioformats2raw?tab=readme-ov-file#usage). 
For example:
```
iohub info /hpc/projects/comp.micro/zebrafish-macrophage/2025-02-15-93a 4dpf/250215_93a_4dpf_em2_sib_2048_002.zarr/0
```
prints
```
Reading file:	 /hpc/projects/comp.micro/zebrafish-macrophage/2025-02-15-93a-4dpf/250215_93a_4dpf_em2_sib_2048_002.zarr/0
Zarr hierarchy:
/
├── 0 (10, 3, 66, 2048, 2048) >u2
├── 1 (10, 3, 66, 1024, 1024) >u2
├── 2 (10, 3, 66, 512, 512) >u2
└── 3 (10, 3, 66, 256, 256) >u2
=== Summary ===
Format:			 omezarr v0.4
Axes:			 t (time); c (channel); z (space); y (space); x (space); 
Channel names:		 ['DIA', 'GFP', …
```
=> Support metadata for `.zarr` converted from `.nd2` using `bioformats2raw` conversion

iohub/ndtiff.py
Use a default (1.0 micrometer) for NDTiff datasets generated by old MM builds. This will be wrong for most datasets but at least rescues the pixels.
=> Set default pixel size for old NDTiff format

.github/workflows/docs.yml, .github/workflows/pr.yml, .github/workflows/test.yml, docs/Makefile, docs/poly.py, docs/source/conf.py, iohub/convert.py, iohub/ngff/__init__.py, setup.cfg
Use sphinx-polyversion to create a different virtual environment when building documentation for each version. This allows documentation to be built simultaneously for versions that have incompatible dependencies.
~(Not working yet)~
Example build: https://github.com/czbiohub-sf/iohub/actions/runs/14072556212/job/39409605319 (the files can be downloaded from the 'upload artifact' step). This PR says 'failure' because the deployment step is not allowed before merging.
=> Use sphinx-polyversion

.github/workflows/docs.yml
Remove the fetching step since the action already runs run the main branch.
=> Remove fetching step in build docs action

iohub/cli/cli.py, iohub/ngff/nodes.py, tests/cli/test_cli.py, tests/ngff/test_ngff.py
Fix #278.
`Position.set_scale` now works for any level, like `Position.set_transform`.
=> Set scale for any coordinate transform

iohub/_deprecated/singlepagetiff.py, iohub/_deprecated/zarrfile.py, iohub/convert.py, iohub/mmstack.py, iohub/reader.py, tests/_deprecated/test_singlepagetiff.py
Fix #292 by wrapping the `ZarrTiffStore`'s storage mapping with `fsspec` so it can be used with zarr-python 3.
Also fixed deprecated TIFF and Zarr readers.
=> Read MMStack with Zarr v3

iohub/ngff/nodes.py, tests/ngff/test_ngff.py
Fix #253.
Case coercing in key lookup only occurs when the platform requires it (i.e. not happening on Linux anymore).
=> Handle case-insensitive platforms in Zarr hierarchy

iohub/ndtiff.py
Allows conversion of:
```
/hpc/instruments/jacobo.isim/Notch/20250501_cldnb-lyn-mScar_myo6b-bactin-gfp_she-h2b-gfp_Notch_LY40nM_timelapse/50_hpf_1
```
=> Catch json decoding error from incomplete NDTIFF

iohub/convert.py, iohub/mm_fov.py, iohub/mmstack.py, iohub/ndtiff.py, tests/test_converter.py
NDTiff does not seem to carry the same information. The unit is always in seconds to prevent mismatch in automated analysis.
Related: #103, #304.
=> Convert time scale for OME-TIFF

.pre-commit-config.yaml
flake8-typing-imports==1.12.0 is not compatible with flake8 6.0.0
=> Update flake8-typing-imports version

iohub/ngff/utils.py
Fixing a bug where writing writing with `_save_transformed` throws an error when all chunks returned by `_apply_transform_to_czyx` are `None`
=> Fix tensorstore empty array handling
