czbiohub-sf/iohub

iohub/reader.py
iohub/zarrfile.py

Infer Zarr dimension separator from NGFF version

---

iohub/ngff.py
tests/ngff/test_ngff.py

Add shorthand to get raw data in NGFF positions

---

examples/single_fov_ome_zarr.py
iohub/ngff.py
tests/ngff/test_ngff.py

Methods for modifying channels in NGFF positions

---

iohub/multipagetiff.py
setup.cfg

Count valid TIFF pages when gathering index map

---

setup.cfg

Update package metadata

---

setup.cfg

Specify minimum zarr-python version

---

examples/large_array_ome_zarr.py
examples/single_fov_ome_zarr.py
iohub/ngff.py
tests/ngff/test_ngff.py

NGFF method to create zero-filled lazy images

---

iohub/convert.py

Skip empty image instead of failing in conversion

---

iohub/ngff.py
tests/ngff/test_ngff.py

Allow different tile data types for NGFF

---

iohub/reader.py

Suppress CLI warning for NGFF v0.1 datasets

---

setup.cfg

Fix https://github.com/czbiohub/iohub/pull/108#discussion_r1167040468

Fix python version requirement

---

examples/coordinate_transform.py

Here I added the coordinate transformation example that performs translation and scaling of the `positions` during read time.

adding a coordinate transformation example.

---

iohub/cli/cli.py
tests/cli/test_cli.py

Fix Windows CLI tests

---

iohub/ngff.py
tests/ngff/test_ngff.py

Set transformation metadata for existing NGFF datasets

---

setup.cfg

Fix version requirement of pydata-sphinx-theme.

Fix theme dependency

---

iohub/clearcontrol.py
iohub/display_utils.py
iohub/ngff.py
iohub/ngff_meta.py

Refactored typing Tuple/List/Dict to tuple/list/dict

---

iohub/ngff.py
tests/ngff/test_ngff.py

Remove state in NGFF plate initialization

---

CONTRIBUTING.md
README.md
docs/source/conf.py
docs/source/contact_us.rst
setup.cfg

Update URLs after organization migration

---

.github/workflows/pr.yml
iohub/clearcontrol.py
iohub/fov.py
iohub/ndtiff.py
setup.cfg
tests/clearcontrol/test_clearcontrol.py
tests/ngff/test_ngff.py

Hi, @ziw-liu .
I also fixed a small bug (using `channels` when it should be `channel_names`) introduced during the PR review.

Inheriting BaseFOV on ClearControlFOV

---

iohub/ngff.py

Hi @ziw-liu and @edyoshikun , 
Could one of you review this one? It's very straightforward.
Thanks,

Scaling chunk size according to pyramid factors

---

CITATION.cff
iohub/upti.py
iohub/zarrfile.py
setup.cfg

Add CITATION.cff for the repo.
Authors: please check your ORCID ID and add information as needed.

Add CITATION.cff

---

.github/workflows/pr.yml
.github/workflows/test.yml

Tweak GitHub actions settings.

Limit action runners

---

tests/ngff/test_ngff.py

Fix #255.
The original test fails due to an ome-zarr-py bug: https://github.com/ome/ome-zarr-py/issues/248#issuecomment-2738712765

Fix test combine FOVs

---

iohub/ngff/models.py
iohub/ngff/nodes.py
iohub/reader.py
tests/cli/test_cli.py

Submit a PR for issue [#270](https://github.com/czbiohub-sf/iohub/issues/270)
@ziw-liu recommended to submit the code snippets that I included in the issue description as a PR.

make nodes.Position.metadata.omero an optional attribute

---

.github/workflows/pr.yml
.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.md
setup.cfg

Bump supported python range to 3.11-3.13

---

tests/ngff/test_ngff.py

Filter test file names on windows

---

.github/workflows/docs.yml

Fix docs deployment failure due to action version mismatch.
See preview (forked) at https://ziw-liu.github.io/iohub/main/index.html

Update deploy pages action

---

CITATION.cff
README.md
docs/source/_static/switcher.json
iohub/reader.py
tests/cli/test_cli.py

Preparing for 0.2.0 release:
- Update citation metadata
- Add DOI badge to README
- Build docs for the new stable version

Update packaging metadata for 0.2.0

---

iohub/ndtiff.py

@akila-14 can you help test this?

Catch truncated unicode error in NDTIFF

---

docs/poly.py
docs/source/_static/switcher.json
docs/source/api/ngff.rst

Fix #309.
Preview: https://ziw-liu.github.io/iohub

Fix docs build for new versions

---

iohub/convert.py
iohub/ndtiff.py

Conversion will continue even if:
* Data at the first position is missing
* Data for all positions at a given timepoint is missing

More robust conversion

---

iohub/ngff/nodes.py
tests/ngff/test_ngff.py

Use store root instead of URI
